#!/bin/bash

# Update and install dependencies
sudo yum update -y
sudo yum install -y python3
sudo pip3 install flask

# Create a directory for the app
mkdir /home/ec2-user/hello-world

# Create the Flask application
cat > /home/ec2-user/hello-world/app.py <<EOF
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello():
    return "Hello World from EC2! This is NO ABSTRACTION"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80)
EOF

# Run the Flask app
nohup python3 /home/ec2-user/hello-world/app.py &
